### ISSUE TITLE
Logo design contribution

### ISSUE THREAD

**Issue by maaudrana** [absunstar/speed-browser#1]
Hallo @absunstar 
I am a designer want to make a logo for this projects.if you have any requirements then let me know.Its free for any open source projects.
Thank you

**Comment by absunstar** [comment]
hello @maaudrana 
we have desinger in our team
but we happy  to your offer
so , we want logo like google chrome logo but cube not cycle
and related to browser name speed
waiting your logo
thanks

**Comment by maaudrana** [comment]
what happened? @absunstar  i am working on that :)

**Comment by absunstar** [comment]
yes , i waiting you
iam just close issues

**Comment by maaudrana** [comment]
![speed-browser-01](https://user-images.githubusercontent.com/34313493/42132907-604cc908-7d42-11e8-9b62-203f2a846304.jpg)

**Comment by absunstar** [comment]
nice desgin
but we want some colors not one color
like chrome & firefox
waiting you

**Comment by maaudrana** [comment]
![speed-browser-01](https://user-images.githubusercontent.com/34313493/42149521-40f082be-7df8-11e8-9f72-c0190839303e.jpg)

**Comment by absunstar** [comment]
sorry , your design not acceptable
but we very happy to join us
thank you
